---
  - name: Playbook
    hosts: vegas,!vegas.home
    become: true
    vars:
      demo: "hello world"
    vars_files:
      varsfiles.yml
    tasks:
      - name: print demo 
        ansible.builtin.debug:
          var: tojas
      - name: Install nmap
        community.general.zypper:
          name: nmap
          state: present
      - name: ensure sshd is running
        ansible.builtin.systemd:
          name: sshd
          state: started

